# Generated by Django 3.0.8 on 2020-07-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CSVDownload',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
